
version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0.9-r11'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    image: dennybaa/helloapp:v0.1.3
    ports:
      - "3030:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017

volumes:
  mongodb_data:
    driver: local
